<!-- Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ -->
<script setup>
import {onMounted,reactive,ref} from 'vue'
import {request} from '../api'
const periods=ref([]),summary=ref({}),error=ref(''),month=new Date().toISOString().slice(0,7)
const form=reactive({employeeNo:'EMP-'+Date.now(),employeeName:'演示员工',period:month,scheduledMinutes:480})
async function load(){const rows=await request(`/api/core/attendance/periods?period=${month}`);periods.value=await Promise.all(rows.map(async p=>({...p,requests:await request(`/api/core/attendance/periods/${p.id}/requests`)})));summary.value=await request(`/api/core/attendance/summary?period=${month}`)}
async function run(fn){try{error.value='';await fn();await load()}catch(e){error.value=e.message}}
async function create(){await run(async()=>{await request('/api/core/attendance/periods',{method:'POST',body:JSON.stringify(form)});form.employeeNo='EMP-'+Date.now()})}
async function act(p,a){await run(async()=>{let path=`/api/core/attendance/periods/${p.id}/${a}`,body;if(a==='work'){path=`/api/core/attendance/periods/${p.id}/entries`;body={idempotencyKey:crypto.randomUUID(),type:'WORK',minutes:p.scheduledMinutes,referenceNo:'CLOCK-'+Date.now()}}if(a==='leave'){path=`/api/core/attendance/periods/${p.id}/requests`;body={requestNo:'LEAVE-'+Date.now(),type:'LEAVE',minutes:60,reason:'个人事务请假'}}if(a==='approve-request'){const pending=p.requests.find(r=>r.status==='PENDING');path=`/api/admin/core/attendance/requests/${pending.id}/review`;body={decision:'APPROVE',remark:'假勤凭证核验通过'}}if(a==='approve'){path=`/api/admin/core/attendance/periods/${p.id}/approve`;body={remark:'主管复核通过'}}if(a==='close'){path=`/api/admin/core/attendance/periods/${p.id}/close`;body={payrollBatchNo:'PAY-'+month}}await request(path,{method:'POST',body:body?JSON.stringify(body):undefined})})}
onMounted(load)
</script>
<template>
  <section class="head"><div><span>TIME GOVERNANCE</span><h3>{{month}} 考勤与假勤审批</h3><p>出勤流水、假勤申请、职责分离审批、异常清零和薪资批次锁定形成完整月结控制。</p></div></section>
  <p class="err" v-if="error">{{error}}</p>
  <section class="metrics"><article><b>{{summary.employees||0}}</b><small>员工台账</small></article><article><b>{{summary.pendingRequests||0}}</b><small>待审批申请</small></article><article><b>{{summary.openExceptions||0}}</b><small>考勤异常</small></article><article><b>{{summary.closedEmployees||0}}</b><small>已月结</small></article></section>
  <form class="create" @submit.prevent="create"><input v-model="form.employeeNo"><input v-model="form.employeeName"><input v-model.number="form.scheduledMinutes" type="number"><button>建立月度台账</button></form>
  <section class="table"><table><thead><tr><th>员工</th><th>应出勤</th><th>实际出勤</th><th>假期/加班</th><th>待审批</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="p in periods" :key="p.id"><td><b>{{p.employeeName}}</b><small>{{p.employeeNo}}</small></td><td>{{p.scheduledMinutes}}</td><td>{{p.workedMinutes}}</td><td>{{p.approvedLeaveMinutes}} / {{p.approvedOvertimeMinutes}}</td><td><span class="pending">{{p.requests.filter(r=>r.status==='PENDING').length}}</span><small v-for="r in p.requests.slice(0,2)" :key="r.id">{{r.type}} {{r.minutes}} 分钟 · {{r.status}}</small></td><td>{{p.status}}</td><td><button v-if="p.status==='DRAFT'&&p.workedMinutes===0" @click="act(p,'work')">登记出勤</button><button v-if="p.status==='DRAFT'" @click="act(p,'leave')">申请请假</button><button v-if="p.requests.some(r=>r.status==='PENDING')" class="review" @click="act(p,'approve-request')">审批申请</button><button v-if="p.status==='DRAFT'" @click="act(p,'submit')">提交月结</button><button v-if="p.status==='SUBMITTED'" @click="act(p,'approve')">审批月结</button><button v-if="p.status==='APPROVED'" @click="act(p,'close')">锁定薪资</button></td></tr></tbody></table></section>
</template>
<style scoped>
.head,.create,.table,.metrics{background:#fff;border:1px solid #dce2df;margin-top:20px;padding:24px}.head span{font-size:11px;letter-spacing:.15em;color:#a56c24}.head h3{margin:6px 0}.head p{margin:0;color:#68777c}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}.metrics article{display:grid}.metrics b{font-size:26px}.metrics small{color:#68777c}.create{display:grid;grid-template-columns:1fr 1fr 1fr auto;gap:10px}.create input{padding:10px;border:1px solid #ccd6d2}.create button,.table button{border:0;background:#235a74;color:white;padding:8px 10px;margin:2px}.table{overflow:auto}.table table{width:100%;border-collapse:collapse}.table th,.table td{text-align:left;padding:11px;border-top:1px solid #edf0ef}.table small{display:block;color:#68777c}.table .review{background:#7d5a52}.pending{display:inline-grid;place-items:center;min-width:24px;height:24px;border-radius:12px;background:#efe1d4;color:#8a4f35}.err{color:#a03f38}@media(max-width:800px){.create,.metrics{grid-template-columns:1fr}}
</style>
