/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.attendance;import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.http.MediaType;import org.springframework.test.web.servlet.*;import java.util.regex.Pattern;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.httpBasic;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest@AutoConfigureMockMvc class AttendanceCoreApiTests{@Autowired MockMvc mvc;
 @Test void monthlyAttendanceRunsThroughLedgerSubmitApproveAndPayrollClose()throws Exception{long id=create("EMP-CORE-1",480);entry(id,"a1","WORK",420);entry(id,"a2","LEAVE",60);post(id,"submit",null,"operator").andExpect(jsonPath("$.data.status").value("SUBMITTED"));post(id,"approve","{\"remark\":\"主管复核通过\"}","admin").andExpect(jsonPath("$.data.status").value("APPROVED"));post(id,"close","{\"payrollBatchNo\":\"PAY-2026-08\"}","admin").andExpect(jsonPath("$.data.status").value("CLOSED"));}
 @Test void unresolvedExceptionBlocksMonthCloseSubmission()throws Exception{long id=create("EMP-CORE-2",480);entry(id,"b1","WORK",480);entry(id,"b2","EXCEPTION",0);post(id,"submit",null,"operator").andExpect(status().isConflict());post(id,"resolve-exception","{\"remark\":\"补签审批通过\"}","operator").andExpect(jsonPath("$.data.openExceptions").value(0));}
 @Test void entryIdempotencyPreventsDoubleCounting()throws Exception{long id=create("EMP-CORE-3",480);entry(id,"same-att","WORK",480);entry(id,"same-att","WORK",480);mvc.perform(get("/api/core/attendance/summary").param("period","2026-08").with(httpBasic("operator","operator123"))).andExpect(status().isOk()).andExpect(jsonPath("$.data.workedMinutes").isNumber());}
 @Test void operatorCannotApprovePayrollResults()throws Exception{long id=create("EMP-CORE-4",480);entry(id,"d1","WORK",480);post(id,"submit",null,"operator");post(id,"approve","{\"remark\":\"越权\"}","operator").andExpect(status().isForbidden());}
 @Test void materialWorkHourVarianceIsRejected()throws Exception{long id=create("EMP-CORE-5",480);entry(id,"e1","WORK",200);post(id,"submit",null,"operator").andExpect(status().isConflict());}
 private long create(String emp,int scheduled)throws Exception{MvcResult r=mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post("/api/core/attendance/periods").with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"employeeNo\":\""+emp+"\",\"employeeName\":\"测试员工\",\"period\":\"2026-08\",\"scheduledMinutes\":"+scheduled+"}")).andExpect(status().isOk()).andReturn();var m=Pattern.compile("\\\"id\\\":(\\d+)").matcher(r.getResponse().getContentAsString());m.find();return Long.parseLong(m.group(1));}
 private void entry(long id,String key,String type,int minutes)throws Exception{mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post("/api/core/attendance/periods/"+id+"/entries").with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"idempotencyKey\":\""+key+"\",\"type\":\""+type+"\",\"minutes\":"+minutes+",\"referenceNo\":\"REF-"+key+"\"}")).andExpect(status().isOk());}
 private ResultActions post(long id,String action,String body,String user)throws Exception{var b=org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post((action.equals("approve")||action.equals("close")?"/api/admin":"/api")+"/core/attendance/periods/"+id+"/"+action).with(httpBasic(user,user.equals("admin")?"admin123":"operator123"));if(body!=null)b.contentType(MediaType.APPLICATION_JSON).content(body);return mvc.perform(b);}
}
