/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.attendance.service;import jakarta.persistence.*;import jakarta.validation.constraints.*;import org.springframework.http.HttpStatus;import org.springframework.security.core.context.SecurityContextHolder;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;import java.time.LocalDateTime;import java.util.*;
@Service public class AttendanceCoreService{private final EntityManager em;public AttendanceCoreService(EntityManager em){this.em=em;}
 @Transactional public AttendancePeriod create(CreatePeriodRequest r){if(!find(r.employeeNo(),r.period()).isEmpty())throw conflict("员工该期间考勤台账已存在");AttendancePeriod p=new AttendancePeriod(r.employeeNo(),r.employeeName(),r.period(),r.scheduledMinutes());em.persist(p);return p;}
 public List<AttendancePeriod> periods(String period,String status){return em.createQuery("select p from AttendanceEmployeePeriod p where (:period is null or p.period=:period) and (:status is null or p.status=:status) order by p.employeeNo",AttendancePeriod.class).setParameter("period",blank(period)?null:period).setParameter("status",blank(status)?null:status).getResultList();}
 public List<AttendanceEntry> entries(Long id){get(id);return em.createQuery("select e from AttendanceLedgerEntry e where e.periodId=:id order by e.createdAt",AttendanceEntry.class).setParameter("id",id).getResultList();}
 @Transactional public AttendanceEntry addEntry(Long id,EntryRequest r){List<AttendanceEntry> old=em.createQuery("select e from AttendanceLedgerEntry e where e.idempotencyKey=:key",AttendanceEntry.class).setParameter("key",r.idempotencyKey()).getResultList();if(!old.isEmpty())return old.getFirst();AttendancePeriod p=locked(id);requireDraft(p);switch(r.type()){case"WORK"->p.workedMinutes+=r.minutes();case"LEAVE"->p.approvedLeaveMinutes+=r.minutes();case"OVERTIME"->p.approvedOvertimeMinutes+=r.minutes();case"EXCEPTION"->p.openExceptions++;default->throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"不支持的考勤流水类型");}AttendanceEntry e=new AttendanceEntry(p.id,r.idempotencyKey(),r.type(),r.minutes(),r.referenceNo(),operator());em.persist(e);return e;}
 @Transactional public AttendancePeriod resolveException(Long id,RemarkRequest r){AttendancePeriod p=locked(id);requireDraft(p);if(p.openExceptions<1)throw conflict("没有待处理考勤异常");p.openExceptions--;p.lastRemark=r.remark();return p;}
 @Transactional public AttendancePeriod submit(Long id){AttendancePeriod p=locked(id);requireDraft(p);if(p.openExceptions>0)throw conflict("仍有未处理考勤异常，不能提交月结");int accounted=p.workedMinutes+p.approvedLeaveMinutes;if(Math.abs(p.scheduledMinutes-accounted)>60)throw conflict("出勤与假期合计偏差超过60分钟");p.status="SUBMITTED";p.submittedAt=LocalDateTime.now();p.submittedBy=operator();return p;}
 @Transactional public AttendancePeriod approve(Long id,RemarkRequest r){AttendancePeriod p=locked(id);if(!"SUBMITTED".equals(p.status))throw conflict("仅已提交考勤可以审批");if(operator().equals(p.submittedBy))throw conflict("提交人与审批人必须职责分离");p.status="APPROVED";p.approvedAt=LocalDateTime.now();p.approvedBy=operator();p.lastRemark=r.remark();return p;}
 @Transactional public AttendancePeriod close(Long id,CloseRequest r){AttendancePeriod p=locked(id);if(!"APPROVED".equals(p.status))throw conflict("仅已批准考勤可以月结");if(blank(r.payrollBatchNo()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"薪资批次号不能为空");p.status="CLOSED";p.payrollBatchNo=r.payrollBatchNo();p.closedAt=LocalDateTime.now();p.closedBy=operator();return p;}
 public MonthlySummary summary(String period){List<AttendancePeriod> all=periods(period,null);return new MonthlySummary(all.size(),all.stream().mapToLong(p->p.scheduledMinutes).sum(),all.stream().mapToLong(p->p.workedMinutes).sum(),all.stream().mapToLong(p->p.approvedLeaveMinutes).sum(),all.stream().mapToLong(p->p.approvedOvertimeMinutes).sum(),all.stream().mapToLong(p->p.openExceptions).sum(),all.stream().filter(p->"CLOSED".equals(p.status)).count());}
 private List<AttendancePeriod>find(String employee,String period){return em.createQuery("select p from AttendanceEmployeePeriod p where p.employeeNo=:e and p.period=:p",AttendancePeriod.class).setParameter("e",employee).setParameter("p",period).getResultList();}private AttendancePeriod get(Long id){AttendancePeriod p=em.find(AttendancePeriod.class,id);if(p==null)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"考勤台账不存在");return p;}private AttendancePeriod locked(Long id){AttendancePeriod p=em.find(AttendancePeriod.class,id,LockModeType.PESSIMISTIC_WRITE);if(p==null)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"考勤台账不存在");return p;}private void requireDraft(AttendancePeriod p){if(!"DRAFT".equals(p.status))throw conflict("非草稿期间不能修改考勤流水");}private boolean blank(String v){return v==null||v.isBlank();}private String operator(){var a=SecurityContextHolder.getContext().getAuthentication();return a==null?"system":a.getName();}private ResponseStatusException conflict(String m){return new ResponseStatusException(HttpStatus.CONFLICT,m);}
 public record CreatePeriodRequest(@NotBlank@Size(max=40)String employeeNo,@NotBlank@Size(max=80)String employeeName,@Pattern(regexp="\\d{4}-\\d{2}")String period,@Positive int scheduledMinutes){}public record EntryRequest(@NotBlank@Size(max=80)String idempotencyKey,@Pattern(regexp="WORK|LEAVE|OVERTIME|EXCEPTION")String type,@PositiveOrZero int minutes,@NotBlank@Size(max=50)String referenceNo){}public record RemarkRequest(@NotBlank@Size(max=500)String remark){}public record CloseRequest(@NotBlank@Size(max=50)String payrollBatchNo){}public record MonthlySummary(long employees,long scheduledMinutes,long workedMinutes,long leaveMinutes,long overtimeMinutes,long openExceptions,long closedEmployees){}
 @Entity(name="AttendanceEmployeePeriod")@Table(name="attendance_employee_periods",uniqueConstraints=@UniqueConstraint(columnNames={"employeeNo","period"}))public static class AttendancePeriod{@Id@GeneratedValue(strategy=GenerationType.IDENTITY)public Long id;@Column(nullable=false,length=40)public String employeeNo;@Column(nullable=false,length=80)public String employeeName;@Column(nullable=false,length=7)public String period;public int scheduledMinutes;public int workedMinutes;public int approvedLeaveMinutes;public int approvedOvertimeMinutes;public int openExceptions;@Column(nullable=false,length=20)public String status;@Column(length=80)public String submittedBy;@Column(length=80)public String approvedBy;@Column(length=80)public String closedBy;@Column(length=50)public String payrollBatchNo;@Column(length=500)public String lastRemark;public LocalDateTime submittedAt;public LocalDateTime approvedAt;public LocalDateTime closedAt;@Version public long version;protected AttendancePeriod(){}AttendancePeriod(String no,String name,String period,int scheduled){this.employeeNo=no;this.employeeName=name;this.period=period;this.scheduledMinutes=scheduled;this.status="DRAFT";}}
 @Entity(name="AttendanceLedgerEntry")@Table(name="attendance_ledger_entries",uniqueConstraints=@UniqueConstraint(columnNames="idempotencyKey"))public static class AttendanceEntry{@Id@GeneratedValue(strategy=GenerationType.IDENTITY)public Long id;public Long periodId;@Column(nullable=false,length=80)public String idempotencyKey;@Column(nullable=false,length=20)public String type;public int minutes;@Column(nullable=false,length=50)public String referenceNo;@Column(nullable=false,length=80)public String createdBy;public LocalDateTime createdAt;protected AttendanceEntry(){}AttendanceEntry(Long periodId,String key,String type,int minutes,String ref,String by){this.periodId=periodId;this.idempotencyKey=key;this.type=type;this.minutes=minutes;this.referenceNo=ref;this.createdBy=by;this.createdAt=LocalDateTime.now();}}
}
